package ua.com.nikiforov.dao.timetables;

import static ua.com.nikiforov.dao.SqlKeyWords.*;

public class StudentsTimetableDAO {

    private static final String ADD_STUDENTS_TIMETABLE = INSERT + TABLE_STUDENTS_TIMETABLE + L_BRACKET
            + COLUMN_STUDENT_TIMETABLE_LESSON_ID + EQUALS_M + Q_MARK + COMA + COLUMN_STUDENT_TIMETABLE_STUDENT_ID
            + EQUALS_M + Q_MARK + COMA + COLUMN_STUDENT_TIMETABLE_TIME + EQUALS_M + Q_MARK + VALUES_3_QMARK;
    private static final String GET_STUDENTS_TIMETABLE_BY_ID = SELECT + ASTERISK + FROM + TABLE_STUDENTS_TIMETABLE
            + WHERE + COLUMN_STUDENT_TIMETABLE_ID + EQUALS_M + Q_MARK;
    private static final String GET_ALL_STUDENTS_TIMETABLE = SELECT + ASTERISK + FROM + TABLE_STUDENTS_TIMETABLE;
    private static final String UPDATE_STUDENTS_TIMETABLE = UPDATE + TABLE_STUDENTS_TIMETABLE + SET
            + COLUMN_STUDENT_TIMETABLE_LESSON_ID + EQUALS_M + Q_MARK + COMA + COLUMN_STUDENT_TIMETABLE_STUDENT_ID
            + EQUALS_M + Q_MARK + COMA + COLUMN_STUDENT_TIMETABLE_TIME + EQUALS_M + Q_MARK + VALUES_3_QMARK;
    private static final String DELETE_STUDENTS_TIMETABLE_BY_ID = DELETE + ASTERISK + FROM + TABLE_STUDENTS_TIMETABLE
            + WHERE + COLUMN_STUDENT_TIMETABLE_ID + EQUALS_M + Q_MARK;
    
    
}
